""" Store train config objects to be used as command line arguments to train.py

- idea is to not change this file after running (although configs will be saved anyway)
- if some values are irrelevant to model, we omit them from the config declaration here for clarity
- this file does not really need to be a python file but is for simplicity
- main purpose of this is to be able to batch submit trainings of many different versions at once
"""

import diffvert.models.train_config as tc

# final models

final_ndive_only_no_track_selection = tc.TrainConfig(
    model_name = "NDIVE",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    num_attention_heads=1,
    jet_flavor_loss = False,
    track_origin_loss = False,
    track_pairing_loss = False,
    vertex_loss = True,
    chi_squared_loss=False,
    clip_vertex=True,
    use_ghost_track=False,
    vertexer = int(tc.Vertexer.NDIVE),
    track_weight_activation = int(tc.WeightActivation.NO_TRACK_SELECTION),
    use_adam=False,
    use_learning_rate_decay_when_stalled=False,
    config_name="final_ndive_only_no_track_selection",
    use_early_stopping=True,
)

final_ndive_only_pf_track_selection = tc.TrainConfig(
    model_name = "NDIVE",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    num_attention_heads=1,
    jet_flavor_loss = False,
    track_origin_loss = False,
    track_pairing_loss = False,
    vertex_loss = True,
    chi_squared_loss=False,
    clip_vertex=True,
    use_ghost_track=False,
    vertexer = int(tc.Vertexer.NDIVE),
    track_weight_activation = int(tc.WeightActivation.PERFECT_WEIGHTS),
    use_adam=False,
    use_learning_rate_decay_when_stalled=False,
    config_name="final_ndive_only_pf_track_selection",
    use_early_stopping=True,
)

final_ndive_only = tc.TrainConfig(
    model_name = "NDIVE",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    num_attention_heads=1,
    jet_flavor_loss = False,
    track_origin_loss = False,
    track_pairing_loss = False,
    vertex_loss = True,
    chi_squared_loss=False,
    clip_vertex=True,
    use_ghost_track=False,
    vertexer = int(tc.Vertexer.NDIVE),
    track_weight_activation=int(tc.WeightActivation.SIGMOID),
    use_adam=False,
    use_learning_rate_decay_when_stalled=False,
    config_name="final_ndive_only",
    use_early_stopping=True,
)

final_ftag_base = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    num_attention_heads=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    clip_vertex=False,
    use_ghost_track=False,
    vertexer = int(tc.Vertexer.NONE),
    use_adam=False,
    use_learning_rate_decay_when_stalled=False,
    config_name="final_ftag_base",
    use_early_stopping=True,
)

final_ftag_ndive = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    num_attention_heads=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    clip_vertex=True,
    use_ghost_track=False,
    vertexer = int(tc.Vertexer.NDIVE),
    track_weight_activation=int(tc.WeightActivation.SIGMOID),
    use_adam=False,
    use_learning_rate_decay_when_stalled=False,
    config_name="final_ftag_ndive",
    use_early_stopping=True,
)

final_ftag_ndive_pf_track_selection = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    num_attention_heads=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    clip_vertex=True,
    use_ghost_track=False,
    vertexer = int(tc.Vertexer.NDIVE),
    track_weight_activation = int(tc.WeightActivation.PERFECT_WEIGHTS),
    use_adam=False,
    use_learning_rate_decay_when_stalled=False,
    config_name="final_ftag_ndive_pf_track_selection",
    use_early_stopping=True,
)

# config for test training. ftag with ndive, sigmoid, etc.
#   liable to change so don't depend on this being saved intelligently
test_train = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SOFTMAX),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="test_train",
)

ftag_base_big_batch = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 500,
    learning_rate = 1e-4,
    num_attention_layers=3,
    num_attention_heads=2,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NONE),
    config_name="ftag_base_big_batch",
    use_adam=True,
    use_learning_rate_decay_when_stalled=True,
)

ftag_ndive_big_batch = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 500,
    learning_rate = 1e-4,
    num_attention_layers=3,
    num_attention_heads=2,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    use_mse_loss=False,
    clip_vertex=True,
    use_ghost_track=False,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NDIVE),
    use_adam=True,
    use_learning_rate_decay_when_stalled=True,
    config_name="ftag_ndive_big_batch",
)

ndive_only = tc.TrainConfig(
    model_name = "NDIVE",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    num_attention_heads=1,
    vertex_loss = True,
    config_name="ndive_only",
    clip_vertex=False,
    use_ghost_track=False,
    track_weight_activation=int(tc.WeightActivation.SIGMOID),
)

ftag_all_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    num_attention_heads=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    normalize_vertex_loss=False,
    chi_squared_loss=False,
    track_weight_loss=False,
    vertexer = int(tc.Vertexer.NDIVE),
    use_ghost_track=False,
    clip_vertex=True,
    use_one_hot_encoding=False,
    use_early_stopping=True,
    use_adam=False,
    use_learning_rate_decay_when_stalled=False,
    config_name="ftag_all_loss",
)

ftag_all_loss_two = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=2,
    num_attention_heads=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    normalize_vertex_loss=False,
    chi_squared_loss=False,
    track_weight_loss=False,
    vertexer = int(tc.Vertexer.NDIVE),
    use_ghost_track=False,
    clip_vertex=True,
    use_one_hot_encoding=False,
    use_early_stopping=True,
    use_adam=False,
    use_learning_rate_decay_when_stalled=False,
    config_name="ftag_all_loss_two",
)

ftag_one_hot = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NDIVE),
    use_one_hot_encoding=True,
    config_name="ftag_one_hot",
)

ftag_ndive_all_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_ndive_all_loss",
)

ftag_ndive_no_ghost = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    use_ghost_track=False,
    clip_vertex=False,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_ndive_no_ghost",
)

ftag_ndive_no_ghost_normalize_vtx_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    normalize_vertex_loss=True,
    chi_squared_loss=False,
    use_ghost_track=False,
    clip_vertex=False,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_ndive_no_ghost_normalize_vtx_loss",
)


ftag_ndive_no_ghost_clip = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    use_ghost_track=False,
    clip_vertex=True,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_ndive_no_ghost_clip",
)


ftag_ndive_add_weights_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    track_weight_loss=True,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_ndive_add_weights_loss",
)

ftag_true_vertex_all_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.TRUE_VERTEX),
    config_name="ftag_true_vertex",
)

ftag_true_weights_all_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.PERFECT_WEIGHTS),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    use_ghost_track=False,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_true_weights",
)

ftag_ndive_all_loss_softmax = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SOFTMAX),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = True,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_ndive_all_loss_softmax",
)

ftag_ndive_no_track_pair_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = False,
    vertex_loss = True,
    chi_squared_loss=False,
    use_ghost_track=False,
    clip_vertex=True,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_ndive_no_track_pair_loss",
)


ftag_ndive_no_vertex_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    pretrained_NDIVE = False,
    track_weight_activation = int(tc.WeightActivation.SIGMOID),
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    use_ghost_track=False,
    clip_vertex=True,
    vertexer = int(tc.Vertexer.NDIVE),
    config_name="ftag_ndive_no_vertex_loss",
)

# base comparison models
ftag_base_one = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NONE),
    config_name="ftag_base_one",
)

ftag_base_one_adam = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=1,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    use_early_stopping=True,
    use_adam=True,
    vertexer = int(tc.Vertexer.NONE),
    config_name="ftag_base_one_adam",
)


ftag_base_big_adam = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 300,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=3,
    num_attention_heads=2,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    use_early_stopping=True,
    use_adam=True,
    vertexer = int(tc.Vertexer.NONE),
    config_name="ftag_base_big_adam",
)


ftag_base_big = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 300,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=3,
    num_attention_heads=2,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    use_early_stopping=True,
    use_adam=False,
    vertexer = int(tc.Vertexer.NONE),
    config_name="ftag_base_big",
)


ftag_base_three_adam = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=3,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    use_early_stopping=True,
    use_adam=True,
    vertexer = int(tc.Vertexer.NONE),
    config_name="ftag_base_three_adam",
)


ftag_two_layer_all_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=2,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NONE),
    config_name="ftag_two_layer_all_loss",
)

ftag_three_layer_all_loss = tc.TrainConfig(
    model_name = "ftag",
    num_epochs = 200,
    samples = "/gpfs/slac/atlas/fs1/d/recsmith/Vertexing/samples/all_flavors/all_flavors",
    batch_size = 100,
    learning_rate = 1e-4,
    num_attention_layers=3,
    jet_flavor_loss = True,
    track_origin_loss = True,
    track_pairing_loss = True,
    vertex_loss = False,
    chi_squared_loss=False,
    vertexer = int(tc.Vertexer.NONE),
    config_name="ftag_three_layer_all_loss",
)
